version: '3.8'

services:

  simple-web-service:
    image: devopsdockeruh/simple-web-service
    ports:
      - 8080:8080
    build: .
    volumes:
      - ./text.log:/usr/src/app/text.log
    command: bundle exec server
    container_name: simple-web-service
