version: '3.8'

services:

  example-frontend:
    image: example-frontend
    ports:
      - 80:5000
    build: .
    container_name: example-frontend
  example-backend:
    image: example-backend
    environment:
      - REDIS_HOST=redis-server
    ports:
      - 8080:8080
    build: .
    container_name: example-backend
  redis-server:
    image: redis:latest
    restart: unless-stopped
    container_name: redis-server
